### ISSUE TITLE
FeMaSR and TensorRT

### ISSUE THREAD

**Issue by dan64** [HolyWu/vs-femasr#3]
I noted that in the master has been removed the support to TensorRT because unusable. 
I'm using FeMaSR with TensorRT and it is working satisfactory well. The images are sharp with more details. 
Like every AI Super Resolution filter sometimes it add some artifacts, but they can be mitigated, see for example this post: https://forum.selur.net/thread-3012-post-17861.html#pid17861
So please keep the support for TensorRT in FeMaSR, because without it the filter is too slow and is practically unusable.
Thanks,
Dan

**Comment by dan64** [comment]
In the case it could be useful, when I'm encoding with FeMaSR using TensorRT is issued the following warning: site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3191.)
return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined]

**Comment by HolyWu** [comment]
Done.
